export default {
    LEAGUES_GET_ALL_SUCCESS: 'LEAGUES_GET_ALL_SUCCESS',
    LEAGUES_GET_ALL_FAIL: 'LEAGUES_GET_ALL_FAIL',
    LEAGUES_GET_ALL_REQUEST: 'LEAGUES_GET_ALL_REQUEST',
    LEAGUES_GET_ALL_CACHE_HIT: 'LEAGUES_GET_ALL_CACHE_HIT',
    LEAGUES_GET_ALL_CACHE_MISS: 'LEAGUES_GET_ALL_CACHE_MISS',

    LEAGUES_UPDATE_SUCCESS: 'LEAGUES_UPDATE_SUCCESS',
    LEAGUES_UPDATE_FAIL: 'LEAGUES_UPDATE_FAIL',

    LEAGUES_ADD_SUCCESS: 'LEAGUES_ADD_SUCCESS',
    LEAGUES_ADD_FAIL: 'LEAGUES_ADD_FAIL',

    LEAGUES_DELETE_SUCCESS: 'LEAGUES_DELETE_SUCCESS',
    LEAGUES_DELETE_FAIL: 'LEAGUES_DELETE_FAIL',

    LEAGUES_GET_SUCCESS: 'LEAGUES_GET_SUCCESS',
    LEAGUES_GET_FAIL: 'LEAGUES_GET_FAIL'
};