version: "3.9"
   
services:
  db:
    image: postgres:12.9-alpine
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_NAME
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - '5432'
  server:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/usr/src/server
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=db
    depends_on:
      - db

volumes:
  pgdata:
