- hosts: all
  sudo: yes
  vars:
    http_port: 80
    max_clients: 200
    client_side: /vagrant/client-react
    server_side: /vagrant/server
    vagrant_dir: /vagrant

    mysql_db_username: project
    mysql_db_password: "Nothing#1"
    htpasswd_file: /etc/httpd/htpasswd/htpasswd
    htpasswd_users:
            - { name: vagrant, passwd: vagrant }
  remote_user: vagrant
  tasks:

  ##############################################
  # Apache
  ##############################################

  - name: Apache and Python WSGI will be present.
    yum: name={{ item }} state=present
    with_items: [httpd, mod_wsgi]
    become: yes
    become_method: sudo
  - name: write the apache config file
    template: src=/vagrant/directory.conf dest=/etc/httpd/conf.d/directory.conf
    notify:
      - restart apache
  - name: Add the Apache user to the vagrant users group.
    command: chown apache:apache /vagrant/server/
    become: yes
    become_method: sudo
  - name: Give Apache execute permissions for VirtualEnv.
    command: chown apache:apache /vagrant/server/db.sqlite3
    become: yes
    become_method: sudo

  - name: Latest version of pip will be present.
    yum: name=python-pip state=latest
    become: yes
    become_method: sudo

  - name: migrate database
    command: python manage.py migrate --noinput chdir={{server_side}}
    become: True
  - name: Django flush database
    command: python manage.py flush --noinput chdir={{server_side}}
    become: True
    become_user: vagrant
  - name: Django collectstatic
    command: python manage.py collectstatic --noinput chdir={{server_side}}
    become: True
    become_user: vagrant
    become_user: vagrant
  - name: create super user
    command: python manage.py create_superuser 'admin' 'admin' 'louis.livingston@gmail.com' chdir={{server_side}}
    become: True
    become_user: vagrant
  - name: populate teams in database
    command: python manage.py populate_teams 2019 chdir={{server_side}}
    become: True
    become_user: vagrant
  - name: Install Watson
    command: python manage.py installwatson chdir={{server_side}}
    become: True
    become_user: vagrant
  - name: Build Watson
    command: python manage.py buildwatson chdir={{server_side}}
    become: True
    become_user: vagrant
  handlers:
    - name: restart apache
      service: name=httpd state=restarted