export default {
    PLAYERS_GET_ALL_SUCCESS: 'PLAYERS_GET_ALL_SUCCESS',
    PLAYERS_GET_ALL_FAIL: 'PLAYERS_GET_ALL_FAIL',
    PLAYERS_GET_ALL_REQUEST: 'PLAYERS_GET_ALL_REQUEST',
    PLAYERS_GET_ALL_CACHE_HIT: 'PLAYERS_GET_ALL_CACHE_HIT',
    PLAYERS_GET_ALL_CACHE_MISS: 'PLAYERS_GET_ALL_CACHE_MISS',

    PLAYERS_GET_SUCCESS: 'PLAYERS_GET_SUCCESS',
    PLAYERS_GET_FAIL: 'PLAYERS_GET_FAIL',

    PLAYERS_GET_SEASON_STATS_SUCCESS: 'PLAYERS_GET_SEASON_STATS_SUCCESS',
    PLAYERS_GET_SEASON_STATS_FAIL: 'PLAYERS_GET_SEASON_STATS_FAIL',

    PLAYERS_GET_CAREER_STATS_SUCCESS: 'PLAYERS_GET_CAREER_STATS_SUCCESS',
    PLAYERS_GET_CAREER_STATS_FAIL: 'PLAYERS_GET_CAREER_STATS_FAIL',

    PLAYERS_GET_FIELDING_STATS_SUCCESS: 'PLAYERS_GET_FIELDING_STATS_SUCCESS',
    PLAYERS_GET_FIELDING_STATS_FAIL: 'PLAYERS_GET_FIELDING_STATS_FAIL'
};