export default {
    SCORECARDS_GET_SUCCESS: 'SCORECARDS_GET_SUCCESS',
    SCORECARDS_GET_FAIL: 'SCORECARDS_GET_FAIL',

    SCORECARDS_GET_BY_GAME_SUCCESS: 'SCORECARDS_GET_BY_GAME_SUCCESS',
    SCORECARDS_GET_BY_GAME_FAIL: 'SCORECARDS_GET_BY_GAME_FAIL',

    SCORECARDS_ADD_SUCCESS: 'SCORECARDS_ADD_SUCCESS',
    SCORECARDS_ADD_FAIL: 'SCORECARDS_ADD_FAIL'
};