# Generated by Django 3.2.11 on 2022-01-15 23:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('league_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=2, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='league_logos')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('birth_country', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.IntegerField()),
                ('birth_state', models.CharField(blank=True, max_length=100, null=True)),
                ('height_inches', models.IntegerField()),
                ('bats', models.CharField(max_length=1)),
                ('name_first', models.CharField(max_length=100)),
                ('birth_city', models.CharField(blank=True, max_length=100, null=True)),
                ('height_feet', models.IntegerField()),
                ('pro_debut_date', models.DateField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('throws', models.CharField(max_length=1)),
                ('position', models.CharField(max_length=1)),
                ('name_use', models.CharField(max_length=100)),
                ('player_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name_last', models.CharField(max_length=100)),
                ('service_years', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('address_city', models.CharField(max_length=100)),
                ('address_country', models.CharField(blank=True, max_length=30, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line3', models.CharField(blank=True, max_length=100, null=True)),
                ('address_province', models.CharField(blank=True, max_length=100, null=True)),
                ('address_state', models.CharField(blank=True, max_length=30, null=True)),
                ('address_zip', models.CharField(blank=True, max_length=15, null=True)),
                ('base_url', models.CharField(max_length=100)),
                ('bis_team_code', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('franchise_code', models.CharField(max_length=10)),
                ('mlb_org', models.CharField(max_length=100)),
                ('mlb_org_id', models.IntegerField(editable=False)),
                ('team_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=100)),
                ('website_url', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='baseball.division')),
            ],
        ),
        migrations.CreateModel(
            name='Team40ManRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.ManyToManyField(to='baseball.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='baseball.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('pitching_stats', django.contrib.postgres.fields.jsonb.JSONField()),
                ('hitting_stats', django.contrib.postgres.fields.jsonb.JSONField()),
                ('fielding_stats', django.contrib.postgres.fields.jsonb.JSONField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='baseball.player')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='baseball.league'),
        ),
    ]
