# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-06 01:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('birth_country', models.CharField(max_length=100)),
                ('death_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('given_name', models.CharField(max_length=30)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('bats', models.CharField(max_length=3)),
                ('throws', models.CharField(max_length=3)),
                ('debut', models.DateField()),
                ('finalGame', models.DateField()),
                ('retroID', models.CharField(max_length=20)),
                ('bbrefID', models.CharField(max_length=20)),
            ],
        ),
    ]
