# Generated by Django 3.2.11 on 2022-01-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='fielding_stats',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='hitting_stats',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='pitching_stats',
        ),
    ]
