# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-06 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='finalGame',
            new_name='final_game',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bbrefID',
        ),
        migrations.RemoveField(
            model_name='player',
            name='retroID',
        ),
        migrations.AddField(
            model_name='player',
            name='bbref_id',
            field=models.CharField(default='take', editable=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='retro_id',
            field=models.CharField(default='take', editable=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
