# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-07 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0004_auto_20190306_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('address_city', models.CharField(max_length=100)),
                ('address_country', models.CharField(blank=True, max_length=30, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line3', models.CharField(blank=True, max_length=100, null=True)),
                ('address_province', models.CharField(blank=True, max_length=100, null=True)),
                ('address_state', models.CharField(blank=True, max_length=30, null=True)),
                ('address_zip', models.CharField(blank=True, max_length=15, null=True)),
                ('base_url', models.CharField(max_length=100)),
                ('bis_team_code', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=10)),
                ('division_abbrev', models.CharField(max_length=10)),
                ('division_full', models.CharField(max_length=100)),
                ('division_id', models.IntegerField(editable=False)),
                ('franchise_code', models.CharField(max_length=10)),
                ('league', models.CharField(choices=[('NL', 'National League'), ('AL', 'American League')], default='NL', max_length=2)),
                ('mlb_org', models.CharField(max_length=100)),
                ('mlb_org_id', models.IntegerField(editable=False)),
                ('team_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=100)),
                ('website_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
