# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-07 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0005_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('league_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=2, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='league_logos')),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.RemoveField(
            model_name='team',
            name='division_abbrev',
        ),
        migrations.RemoveField(
            model_name='team',
            name='division_full',
        ),
        migrations.RemoveField(
            model_name='team',
            name='division_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='franchise_code',
        ),
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseball.Division'),
        ),
        migrations.AddField(
            model_name='division',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseball.League'),
        ),
    ]
