# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-07 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0006_auto_20190307_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='franchise_code',
            field=models.CharField(default='NLE', max_length=10),
            preserve_default=False,
        ),
    ]
