# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-08 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0008_auto_20190308_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='service_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
