# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-08 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0010_auto_20190308_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
