# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-08 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0012_auto_20190308_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=1),
        ),
    ]
