# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-11 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0013_auto_20190308_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='baseball.Player'),
        ),
    ]
