export default {
    SET_CURRENT: 'SET_CURRENT',
    SET_CURRENT_FAIL: 'SET_CURRENT_FAIL',
    CLEAR_CURRENT: 'CLEAR_CURRENT',
    CLEAR_CURRENT_FAIL: 'CLEAR_CURRENT_FAIL',

    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAIL: 'LOGOUT_FAIL'
}