# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-05 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='file_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], default='audio', max_length=5),
        ),
    ]
