# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-07 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0002_mediaitem_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSubtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('source_language', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=b'')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialibrary.MediaItem')),
            ],
        ),
    ]
