# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-08 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0003_videosubtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='videosubtitle',
            name='media_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='medialibrary.MediaItem'),
        ),
    ]
