# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-10 19:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medialibrary', '0004_auto_20181008_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
