# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-12 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0005_mediaitem_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
