# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-12 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0006_mediaitem_uploaded_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
