# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-12 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medialibrary', '0007_mediaitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented_on', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('publish', models.BooleanField(default=True)),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialibrary.MediaItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
