# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-13 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medialibrary', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='loves',
            field=models.ManyToManyField(blank=True, related_name='comment_loves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='loves',
            field=models.ManyToManyField(blank=True, related_name='media_loves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='media_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='medialibrary.MediaItem'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
