# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medialibrary', '0009_auto_20181013_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='love_count',
            field=models.IntegerField(default=0),
        ),
    ]
