# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-09 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteauth', '0003_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='teams',
            field=models.TextField(default=''),
        ),
    ]
