# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-12 23:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteauth', '0005_auto_20190409_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='teams',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=[], size=None),
        ),
    ]
