# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-13 00:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteauth', '0006_auto_20190412_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='teams',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, size=None),
        ),
    ]
