# Generated by Django 3.0.7 on 2020-10-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteauth', '0007_auto_20190413_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
