# Generated by Django 3.0.7 on 2021-04-22 22:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteauth', '0008_auto_20201018_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='teams',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, null=True, size=None),
        ),
    ]
