# Generated by Django 3.2.11 on 2022-01-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteauth', '0009_auto_20210422_2221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
