export default {
    TEAMS_GET_ALL_SUCCESS: 'TEAMS_GET_ALL_SUCCESS',
    TEAMS_GET_ALL_FAIL: 'TEAMS_GET_ALL_FAIL',
    TEAMS_GET_ALL_REQUEST: 'TEAMS_GET_ALL_REQUEST',
    TEAMS_GET_ALL_CACHE_HIT: 'TEAMS_GET_ALL_CACHE_HIT',
    TEAMS_GET_ALL_CACHE_MISS: 'TEAMS_GET_ALL_CACHE_MISS',

    TEAMS_GET_SUCCESS: 'TEAMS_GET_SUCCESS',
    TEAMS_GET_FAIL: 'TEAMS_GET_FAIL',

    TEAMS_GET_ROSTER_SUCCESS: 'TEAMS_GET_ROSTER_SUCCESS',
    TEAMS_GET_ROSTER_FAIL: 'TEAMS_GET_ROSTER_FAIL',

    TEAMS_GET_COACHES_SUCCESS: 'TEAMS_GET_COACHES_SUCCESS',
    TEAMS_GET_COACHES_FAIL: 'TEAMS_GET_COACHES_FAIL',

    TEAMS_GET_BY_DATE_SUCCESS: 'TEAMS_GET_BY_DATE_SUCCESS',
    TEAMS_GET_BY_DATE_FAIL: 'TEAMS_GET_BY_DATE_FAIL'
};