export default {
    DIVISIONS_GET_ALL_SUCCESS: 'DIVISIONS_GET_ALL_SUCCESS',
    DIVISIONS_GET_ALL_FAIL: 'DIVISIONS_GET_ALL_FAIL',
    DIVISIONS_GET_ALL_REQUEST: 'DIVISIONS_GET_ALL_REQUEST',
    DIVISIONS_GET_ALL_CACHE_HIT: 'DIVISIONS_GET_ALL_CACHE_HIT',
    DIVISIONS_GET_ALL_CACHE_MISS: 'DIVISIONS_GET_ALL_CACHE_MISS',

    DIVISIONS_GET_SUCCESS: 'DIVISIONS_GET_SUCCESS',
    DIVISIONS_GET_FAIL: 'DIVISIONS_GET_FAIL'
};