# Generated by Django 3.2.11 on 2022-01-16 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecard',
            name='data',
        ),
    ]
