# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-11 16:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to=settings.AUTH_USER_MODEL),
        ),
    ]
